### ISSUE TITLE
Trouble Storing Animations

### ISSUE THREAD

**Issue by chamons** [leod/pareen#11]
I can't find a way of storing animations outside of the scope of a function.

Example:

```rust
type FloatAnimation = pareen::Anim<dyn pareen::Fun<T = f32, V = f32>>;

enum Animation {
    Position { x: FloatAnimation },
}
```
> error[E0277]: the size for values of type `(dyn pareen::Fun<V = f32, T = f32> + 'static)` cannot be known at compilation time
  --> FILE:7:16
   |
7  |     Position { x: FloatAnimation},
   |                ^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time

```rust
type FloatAnimation = pareen::Anim<dyn pareen::Fun<T = f32, V = f32>>;
enum Animation2 {
    Position { x: Box<FloatAnimation> },
}
```
> error[E0277]: the size for values of type `(dyn pareen::Fun<V = f32, T = f32> + 'static)` cannot be known at compilation time
  --> FILE:7:16
   |
7  |     Position { x: Box<FloatAnimation>},
   |                ^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time

I'm still pretty new to rust, am I missing something?

I came across [this PR](https://github.com/leod/pareen/pull/3), does that means this is in work?

**Comment by leod** [comment]
Indeed, with https://github.com/leod/pareen/pull/3/files you would be able to store an `AnimBox<f32, f32>` inside your `Animation2` type.

However, please note that this is not how pareen is usually used. You can think of pareen's `Anim` type as something similar to rust's Iterators: they are something that you construct (by chaining operations like `Iterator::map` or `Anim::map`) and then consume locally. I believe boxed iterators are rarely seen in rust.

I should really make this clear in the readme. I actually consider the whole design of pareen experimental, and I'm not sure if I'm still happy with the design.

**Comment by chamons** [comment]
Being able to chain them together:

```
let anim2 = anim1.seq(0.7, pareen::prop(0.25) + 0.5);
```

to me suggested you could store one as state, and that iterate it each frame to calculate the new location.

**Comment by leod** [comment]
I've called this out more prominently now in the readme. Thank you for reporting this!
