### ISSUE TITLE
Documentation example broken in rust 2018

### ISSUE THREAD

**Issue by chamons** [leod/pareen#12]
From: https://docs.rs/pareen/0.2.3/pareen/fn.lerp.html

```rust
let anim = pareen::lerp(5.0f32, 10.0);
```

> 29  |              let anim = pareen::lerp(5.0f32, 10.0);
    |                  ----   ^^^^^^^^^^^^ cannot infer type for type parameter `T` declared on the function `lerp`
    |                  |
    |                  consider giving `anim` the explicit type `pareen::Anim<impl pareen::Fun>`, where the type parameter `T` is specified

**Comment by leod** [comment]
Thank you for your report!

I think this is as expected. Pareen's `Anim` type is generic over the time `T` and value type `V` and in your example rust has no way to find out what `T` is. If you add a call to `eval` (as is done in the example in the call to `assert_approx_eq`), it compiles:
```rust
fn main()  {
    let anim = pareen::lerp(5.0, 10.0); 
    let x = anim.eval(0.0);
}
```
